import type { Metadata } from "next";
import "./globals.css";
import "prismjs/themes/prism-tomorrow.css";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import Header from "@/app/_components/Header";
import PrismInit from "@/app/_components/PrismInit";
import MermaidInit from "@/app/_components/MermaidInit";

export const metadata: Metadata = {
  title: "NextBlogApp",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

const RootLayout: React.FC<Props> = (props) => {
  const { children } = props;
  return (
    <html lang="ja">
      <body>
        <Header />
        <PrismInit />
        <MermaidInit />
        <div className="mx-4 mt-2 mb-8 max-w-2xl md:mx-auto">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
